// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Nyxon.Core.Models.Vaults;
using Nyxon.Server.Data;

#nullable disable

namespace Nyxon.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109162731_RemovedUselessIdentityKeyFromHandshake")]
    partial class RemovedUselessIdentityKeyFromHandshake
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nyxon.Server.Models.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePtr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.Property<byte[]>("WrappedDek")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("MessageId");

                    b.HasIndex("OwnerId");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("Nyxon.Server.Models.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastMessageAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastSequenceNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("User1Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("User2Id")
                        .HasColumnType("uuid");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("LastMessageAt");

                    b.HasIndex("Id", "LastSequenceNumber");

                    b.HasIndex("User1Id", "User2Id")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Nyxon.Server.Models.ConversationUser", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRead")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId", "ConversationId");

                    b.ToTable("ConversationUsers");
                });

            modelBuilder.Entity("Nyxon.Server.Models.ConversationVault", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("RecvCounter")
                        .HasColumnType("integer");

                    b.Property<int>("SendCounter")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<ConversationVaultData>("VaultData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationVaults");
                });

            modelBuilder.Entity("Nyxon.Server.Models.Handshake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OpkId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PublicAgreementKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PublicEphemeralKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("SpkId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uuid");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("InitiatorId");

                    b.HasIndex("OpkId");

                    b.HasIndex("SpkId");

                    b.HasIndex("TargetUserId", "CreatedAt");

                    b.ToTable("Handshakes");
                });

            modelBuilder.Entity("Nyxon.Server.Models.InviteCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("InviteCodes");
                });

            modelBuilder.Entity("Nyxon.Server.Models.MessageMetadata", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KvKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MessageIndex")
                        .HasColumnType("integer");

                    b.Property<int>("RotationIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uuid");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("KvKey")
                        .IsUnique();

                    b.HasIndex("SenderId");

                    b.ToTable("MessageMetadata");
                });

            modelBuilder.Entity("Nyxon.Server.Models.OneTimePrekey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("EncryptedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<bool>("Used")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("OneTimePrekeys");
                });

            modelBuilder.Entity("Nyxon.Server.Models.RatchetSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedSessionKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("RotationIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId", "ConversationId", "Type", "RotationIndex")
                        .IsUnique();

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "ConversationId", "Type", "RotationIndex"), new[] { "EncryptedSessionKey" });

                    b.ToTable("RatchetSnapshots");
                });

            modelBuilder.Entity("Nyxon.Server.Models.SignedPrekey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("EncryptedKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("Signature")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("SignedPrekeys");
                });

            modelBuilder.Entity("Nyxon.Server.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Admin")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanCreateInvites")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PublicAgreementKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PublicIdentityKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Nyxon.Server.Models.UserVault", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("PassphraseSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PrivateAgreementKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PrivateIdentityKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("VaultKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<short>("Version")
                        .HasColumnType("smallint");

                    b.HasKey("UserId");

                    b.ToTable("UserVaults");
                });

            modelBuilder.Entity("Nyxon.Server.Models.Attachment", b =>
                {
                    b.HasOne("Nyxon.Server.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.MessageMetadata", "Message")
                        .WithMany("Attachments")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Message");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Nyxon.Server.Models.ConversationUser", b =>
                {
                    b.HasOne("Nyxon.Server.Models.Conversation", "Conversation")
                        .WithMany("ConversationUsers")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.User", "User")
                        .WithMany("ConversationUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nyxon.Server.Models.ConversationVault", b =>
                {
                    b.HasOne("Nyxon.Server.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.User", "User")
                        .WithMany("ConversationVaults")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nyxon.Server.Models.Handshake", b =>
                {
                    b.HasOne("Nyxon.Server.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.User", "Initiator")
                        .WithMany()
                        .HasForeignKey("InitiatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.OneTimePrekey", "Opk")
                        .WithMany()
                        .HasForeignKey("OpkId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Nyxon.Server.Models.SignedPrekey", "Spk")
                        .WithMany()
                        .HasForeignKey("SpkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.User", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Initiator");

                    b.Navigation("Opk");

                    b.Navigation("Spk");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("Nyxon.Server.Models.MessageMetadata", b =>
                {
                    b.HasOne("Nyxon.Server.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Nyxon.Server.Models.OneTimePrekey", b =>
                {
                    b.HasOne("Nyxon.Server.Models.User", "User")
                        .WithMany("OneTimePrekeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nyxon.Server.Models.RatchetSnapshot", b =>
                {
                    b.HasOne("Nyxon.Server.Models.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Nyxon.Server.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nyxon.Server.Models.SignedPrekey", b =>
                {
                    b.HasOne("Nyxon.Server.Models.User", "User")
                        .WithMany("SignedPrekeys")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nyxon.Server.Models.UserVault", b =>
                {
                    b.HasOne("Nyxon.Server.Models.User", "User")
                        .WithOne("UserVault")
                        .HasForeignKey("Nyxon.Server.Models.UserVault", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Nyxon.Server.Models.Conversation", b =>
                {
                    b.Navigation("ConversationUsers");
                });

            modelBuilder.Entity("Nyxon.Server.Models.MessageMetadata", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("Nyxon.Server.Models.User", b =>
                {
                    b.Navigation("ConversationUsers");

                    b.Navigation("ConversationVaults");

                    b.Navigation("OneTimePrekeys");

                    b.Navigation("SignedPrekeys");

                    b.Navigation("UserVault")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
