services:
  postgres:
    ports:
      - "${POSTGRES_PORT}:5432"

  valkey:
    ports:
      - "${VALKEY_PORT}:6379"

  server:
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

  caddy:
    image: caddy:latest
    ports:
      # Map External 8000 -> Internal 80
      - "8000:80" 
    volumes:
      - ./Caddyfile.dev:/etc/caddy/Caddyfile
    extra_hosts:
      # This allows Caddy (in Docker) to talk to your WSL2 (Client)
      - "host.docker.internal:host-gateway"
    depends_on:
      - server