services:
  postgres:
    image: postgres:18
    container_name: ${POSTGRES_HOST}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql

  valkey:
    image: valkey/valkey:9
    container_name: ${VALKEY_HOST}
    restart: unless-stopped
    volumes:
      - valkey_data:/data

  server:
    image: nyxon_server
    build:
      context: .
      dockerfile: ./Nyxon.Server/Dockerfile
    container_name: ${SERVER_HOST}
    restart: unless-stopped
    depends_on:
      - postgres
      - valkey
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      VALKEY_HOST: ${VALKEY_HOST}
      VALKEY_PORT: 6379

volumes:
  postgres_data:
  valkey_data:
